/**
 * Multi-region TURN cluster blueprint (coturn-compatible).
 * Infrastructure-only: emits config fragments for deployment; does not touch app WebRTC logic.
 */

export type TurnRegionId = "us-east" | "eu-west" | "asia-south" | string;

export interface TurnClusterSpec {
  readonly regions: TurnRegionId[];
  readonly fallbackRouting: boolean;
  readonly latencyBasedSelection: boolean;
  /** Shared secret for long-term credentials (rotate in KMS). */
  readonly sharedSecretRef: string;
  /** Realm advertised to clients (RFC 5766). */
  readonly realm: string;
  /** UDP listener ports per node (host networking / NLB). */
  readonly udpPorts: readonly number[];
  /** Plain TCP relay (fallback). */
  readonly tcpRelayPort: number;
  /** TLS TURN (TURNS) — typically 5349. */
  readonly tlsTurnPort: number;
  /** Certificate paths on TURN VM/pod (mounted from secret). */
  readonly tlsCertPath: string;
  readonly tlsKeyPath: string;
  /** Max relay bandwidth per allocation (bits/s), ops-tunable. */
  readonly maxBandwidthBps: number;
}

/** Canonical production-shaped cluster matching Agent 9 spec. */
export const DEFAULT_TURN_CLUSTER_SPEC: TurnClusterSpec = {
  regions: ["us-east", "eu-west", "asia-south"],
  fallbackRouting: true,
  latencyBasedSelection: true,
  sharedSecretRef: "${TURN_SHARED_SECRET}",
  realm: "ui-builder.turn.example.com",
  udpPorts: [3478, 3479],
  tcpRelayPort: 3478,
  tlsTurnPort: 5349,
  tlsCertPath: "/etc/coturn/fullchain.pem",
  tlsKeyPath: "/etc/coturn/privkey.pem",
  maxBandwidthBps: 50_000_000,
};

export interface CoturnRegionNode {
  readonly region: TurnRegionId;
  /** Public hostname or Anycast VIP clients resolve to. */
  readonly externalHostname: string;
  /** Internal IP for STUN XOR-MAPPED-ADDRESS if needed. */
  readonly advertisedRelayIp?: string;
}

export interface CoturnGeneratedConfig {
  readonly region: TurnRegionId;
  readonly coturnIni: string;
}

/**
 * Build coturn-compatible config text for one regional node.
 * Uses TLS + UDP + TCP per stack requirements.
 */
export function buildCoturnConfigForRegion(
  spec: TurnClusterSpec,
  node: CoturnRegionNode,
): CoturnGeneratedConfig {
  const udpListeningPort = spec.udpPorts[0] ?? 3478;
  const altUdp = spec.udpPorts[1];

  const lines = [
    `# region=${node.region} generated by turnClusterConfig`,
    `listening-ip=0.0.0.0`,
    `relay-ip=${node.advertisedRelayIp ?? "$RELAY_IP"}`,
    `listening-port=${udpListeningPort}`,
    altUdp !== undefined ? `alt-listening-port=${altUdp}` : "",
    `tls-listening-port=${spec.tlsTurnPort}`,
    `tcp-proxy-port=${spec.tcpRelayPort}`,
    "",
    `# TLS for TURNS`,
    `cert=${spec.tlsCertPath}`,
    `pkey=${spec.tlsKeyPath}`,
    "",
    `# Long-term credentials (prefer REST / ephemeral; coturn use-auth-secret)`,
    `realm=${spec.realm}`,
    `use-auth-secret`,
    `static-auth-secret=${spec.sharedSecretRef}`,
    "",
    `# Limits`,
    `max-bps=${spec.maxBandwidthBps}`,
    `no-multicast-peers`,
    `no-cli`,
    "",
    `# Logging / prod`,
    `syslog`,
    `simple-log`,
    "",
    `# Fingerprint for WebRTC compat`,
    `fingerprint`,
    `lt-cred-mech`,
    "",
    `# Relay over UDP + TCP`,
    `no-tlsv1`,
    `no-tlsv1_1`,
  ].filter(Boolean);

  return {
    region: node.region,
    coturnIni: lines.join("\n"),
  };
}

export type TURNCluster = Pick<
  TurnClusterSpec,
  "regions" | "fallbackRouting" | "latencyBasedSelection"
>;

export function createTurnClusterFromSpec(spec: TurnClusterSpec): TURNCluster {
  return {
    regions: [...spec.regions],
    fallbackRouting: spec.fallbackRouting,
    latencyBasedSelection: spec.latencyBasedSelection,
  };
}
